// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckFlipsDB(arg1:string):Promise<Array<backend.FlipRowItem>>;

export function ExportStatistics(arg1:number,arg2:number,arg3:string):Promise<boolean>;

export function FlipPatronDB(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;
