// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFlipsDB(arg1) {
  return window['go']['main']['App']['CheckFlipsDB'](arg1);
}

export function CheckVersion() {
  return window['go']['main']['App']['CheckVersion']();
}

export function DeclinePatronDB(arg1) {
  return window['go']['main']['App']['DeclinePatronDB'](arg1);
}

export function DeleteFlip(arg1, arg2) {
  return window['go']['main']['App']['DeleteFlip'](arg1, arg2);
}

export function ExportStatistics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportStatistics'](arg1, arg2, arg3);
}

export function FlipPatronDB(arg1) {
  return window['go']['main']['App']['FlipPatronDB'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveLogs(arg1) {
  return window['go']['main']['App']['SaveLogs'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}
