// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckFlipsDB(arg1:string):Promise<Array<backend.FlipRowItem>>;

export function CheckVersion():Promise<string>;

export function DeclinePatronDB(arg1:string):Promise<void>;

export function DeleteFlip(arg1:string,arg2:number):Promise<boolean>;

export function ExportStatistics(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<boolean>;

export function FlipPatronDB(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SaveLogs(arg1:string):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;
